package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-04-07T00:23:32.624-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://soap/", name = "InterfaceWebServiceExample")
@XmlSeeAlso({ObjectFactory.class})
public interface InterfaceWebServiceExample {

    @WebMethod
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://soap/", className = "soap.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://soap/", className = "soap.ListarPersonasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<soap.Persona> listarPersonas();

    @WebMethod
    @RequestWrapper(localName = "sumar", targetNamespace = "http://soap/", className = "soap.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://soap/", className = "soap.SumarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
